trainer: # trainer arguments
  logger: true
  enable_checkpointing: true
  max_epochs: 250
  accelerator: cuda
  devices:  1
  precision: 16

model:
  class_path:
  dict_kwargs:
    lr: 1e-2
    weight_decay: 1e-2

data:
  class_path: data.DataModule
  init_args:
    type_dataset: mnist
    batch_size: 12
    pin_memory: true
    num_workers: 8
