trainer: # trainer arguments
  logger: true
  enable_checkpointing: true
  max_epochs: 250
  accelerator: cuda
  devices:  1
  precision: 16

model:
  class_path: synthetic.model.Model
  dict_kwargs:
    lr: 1e-2
    weight_decay: 1e-2
    hidden_size: 8
    layers: 4

data:
  class_path: synthetic.dataset.DataModule
  init_args:
    batch_size: 12
    pin_memory: true
    num_workers: 8
    train_p: 0.8
    step_size: 5

